### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flyingDandelionYD** [microsoft/xcodeproj#1]
when i use :  xcodeproj.XcodeProject("/Users/xxx/Desktop/Iphone/xxx.xcodeproj")
 
it prints:

raise DeserializeException(
deserialize.exceptions.DeserializeException: Cannot deserialize '<class 'str'>' to '<enum 'PBXProductType'>' for 'typing.Dict[str, xcodeproj.pbxobject.PBXObject].09E3D8931DD42DD600E1E053.product_type

how to solve it ,thanks!

**Comment by dalemyers** [comment]
Hey @flyingDandelionYD, any update here? If not, I'll close this issue. Thanks!
